-- MTIX-95.4 hub schema (file 015).
-- Executed by the transport under PG advisory-lock single-flight,
-- auto-applied in lexical order via migrations.Files(). DO NOT run manually;
-- the hub owner applies it with `mtix sync init`.
--
-- Index for the cursor pass of `mtix sync pull` and for `mtix sync clone`
-- (ADR-006 D6, D39).
--
-- Both page through the hub log by the keyset (lamport_clock, event_id):
--
--     WHERE (lamport_clock, event_id) > ($1, $2)
--     ORDER BY lamport_clock, event_id
--     LIMIT $3
--
-- The event id breaks Lamport ties, so events that share a Lamport clock
-- across a page boundary are all pulled. This index serves each page from
-- the cursor on, in order. Until it exists (a hub whose owner has not yet
-- re-run `mtix sync init` after upgrading) pulls return the same events,
-- but each page scans and sorts the whole of sync_events.
--
-- Migrate applies every file in ONE transaction, so this index is built
-- inside it, not concurrently. That transaction already holds an ACCESS
-- EXCLUSIVE lock on sync_events, taken by the ADD COLUMN IF NOT EXISTS
-- statements of 010 and 013, until it commits: pushes and pulls both wait
-- for `mtix sync init`. A push or pull that waits past its 10-second
-- statement timeout is retried, up to 5 attempts in all (about 50
-- seconds), so it normally completes once `mtix sync init` finishes; it
-- fails only if the wait outlasts its retries, and then nothing is lost
-- and the next one succeeds. On a large hub the first build of this index
-- makes the wait longer, so run `mtix sync init` when a pause in sync is
-- acceptable. Once the index exists the statement only checks for it.
--
-- Additive and idempotent: IF NOT EXISTS makes a re-run a no-op, and no
-- column, constraint or row is touched.

CREATE INDEX IF NOT EXISTS idx_sync_events_lamport_event_id
    ON sync_events (lamport_clock, event_id);
