// Copyright 2025-2026 HyperSWE
// SPDX-License-Identifier: Apache-2.0

package docs

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/hyper-swe/mtix/internal/model"
)

// TestDocGen_ProducesAll11Files verifies all 11 doc files are generated.
func TestDocGen_ProducesAll11Files(t *testing.T) {
	tmpDir := t.TempDir()
	outDir := filepath.Join(tmpDir, "docs")

	data := minimalTemplateData()
	gen := mustCreateGenerator(t, outDir, data)

	results, err := gen.Generate(false)
	require.NoError(t, err)
	assert.Len(t, results, 11, "should produce 11 files")

	for _, r := range results {
		assert.Equal(t, "generated", r.Action, "file %s should be generated", r.File)
		path := filepath.Join(outDir, r.File)
		assert.FileExists(t, path, "file %s should exist", r.File)
	}
}

// TestDocGen_AutoGenerated_AlwaysRegenerated verifies auto-generated files are always updated.
func TestDocGen_AutoGenerated_AlwaysRegenerated(t *testing.T) {
	tmpDir := t.TempDir()
	outDir := filepath.Join(tmpDir, "docs")

	data := minimalTemplateData()
	gen := mustCreateGenerator(t, outDir, data)

	// First generation.
	_, err := gen.Generate(false)
	require.NoError(t, err)

	// Modify an auto-generated file.
	cliRefPath := filepath.Join(outDir, "CLI_REFERENCE.md")
	err = os.WriteFile(cliRefPath, []byte("modified content"), 0o644)
	require.NoError(t, err)

	// Second generation — auto-generated files should be updated.
	results, err := gen.Generate(false)
	require.NoError(t, err)

	for _, r := range results {
		if r.File == "CLI_REFERENCE.md" || r.File == "STATUS_MACHINE.md" || r.File == "TROUBLESHOOTING.md" {
			assert.Equal(t, "updated", r.Action,
				"auto-generated file %s should be updated", r.File)
		}
	}

	// Verify content was regenerated.
	content, err := os.ReadFile(cliRefPath)
	require.NoError(t, err)
	assert.NotEqual(t, "modified content", string(content))
}

// TestDocGen_TemplateBased_SkipsExisting verifies template files are not overwritten.
func TestDocGen_TemplateBased_SkipsExisting(t *testing.T) {
	tmpDir := t.TempDir()
	outDir := filepath.Join(tmpDir, "docs")

	data := minimalTemplateData()
	gen := mustCreateGenerator(t, outDir, data)

	// First generation.
	_, err := gen.Generate(false)
	require.NoError(t, err)

	// Modify a template-based file.
	agentsPath := filepath.Join(outDir, "AGENTS.md")
	err = os.WriteFile(agentsPath, []byte("custom human edits"), 0o644)
	require.NoError(t, err)

	// Second generation without force — should skip.
	results, err := gen.Generate(false)
	require.NoError(t, err)

	for _, r := range results {
		if r.File == "AGENTS.md" {
			assert.Equal(t, "skipped", r.Action,
				"template-based file should be skipped")
		}
	}

	// Verify content preserved.
	content, err := os.ReadFile(agentsPath)
	require.NoError(t, err)
	assert.Equal(t, "custom human edits", string(content))
}

// TestDocGen_Force_RegeneratesAll verifies --force regenerates everything.
func TestDocGen_Force_RegeneratesAll(t *testing.T) {
	tmpDir := t.TempDir()
	outDir := filepath.Join(tmpDir, "docs")

	data := minimalTemplateData()
	gen := mustCreateGenerator(t, outDir, data)

	// First generation.
	_, err := gen.Generate(false)
	require.NoError(t, err)

	// Second generation with force.
	results, err := gen.Generate(true)
	require.NoError(t, err)

	for _, r := range results {
		assert.NotEqual(t, "skipped", r.Action,
			"with --force, file %s should not be skipped", r.File)
	}
}

// TestDocGen_OutputInDocsDirectory verifies files are in the docs/ directory.
func TestDocGen_OutputInDocsDirectory(t *testing.T) {
	tmpDir := t.TempDir()
	outDir := filepath.Join(tmpDir, "project", "docs")

	data := minimalTemplateData()
	gen := mustCreateGenerator(t, outDir, data)

	_, err := gen.Generate(false)
	require.NoError(t, err)

	// Verify output directory was created.
	info, err := os.Stat(outDir)
	require.NoError(t, err)
	assert.True(t, info.IsDir())
}

// TestAllDocFiles_Returns11 verifies the doc file list has all 11 entries.
func TestAllDocFiles_Returns11(t *testing.T) {
	files := AllDocFiles()
	assert.Len(t, files, 11)

	names := make(map[string]bool)
	for _, f := range files {
		names[f.Name] = true
		assert.NotEmpty(t, f.TemplateName, "file %s must have a template", f.Name)
	}

	// Verify expected files.
	expected := []string{
		"AGENTS.md", "CLAUDE.md", "SKILL.md", "CLI_REFERENCE.md",
		"STATUS_MACHINE.md", "WORKFLOWS.md", "CONTEXT_CHAIN.md",
		"BLOCKED_HANDLING.md", "SESSION_PROTOCOL.md", "PATTERNS.md",
		"TROUBLESHOOTING.md",
	}
	for _, name := range expected {
		assert.True(t, names[name], "missing doc file: %s", name)
	}
}

// mustCreateGenerator creates a generator using the embedded templates.
func mustCreateGenerator(t *testing.T, outDir string, data *TemplateData) *Generator {
	t.Helper()

	// Find the templates directory relative to this test file.
	// Templates are in internal/docs/templates/
	tmplDir := "templates"

	gen, err := NewGenerator(tmplDir, outDir, data, nil)
	require.NoError(t, err)
	return gen
}

// minimalTemplateData creates minimal data for testing.
func minimalTemplateData() *TemplateData {
	return &TemplateData{
		ProjectPrefix: "TEST",
		Version:       "0.1.0-test",
		Commands: []CommandInfo{
			{Name: "mtix", Use: "mtix", Short: "Micro issue manager"},
		},
		Transitions: IntrospectStateMachine(),
		Statuses:    []model.Status{model.StatusOpen, model.StatusInProgress, model.StatusDone},
		MCPTools: []MCPToolInfo{
			{Name: "mtix_create", Description: "Create a node"},
		},
		ConfigKeys: []string{"prefix", "api.bind"},
		ErrorCodes: []string{"ErrNotFound", "ErrInvalidInput"},
	}
}
