// Copyright 2025-2026 HyperSWE
// SPDX-License-Identifier: Apache-2.0

// Package docs implements the documentation generation engine per FR-13.1.
// Generates agent-facing documentation from runtime introspection data.
package docs

import (
	"fmt"
	"io/fs"
	"log/slog"
	"os"
	"path/filepath"
	"text/template"
)

// DocType classifies how a doc file is managed.
type DocType int

const (
	// AutoGenerated files are always regenerated on mtix docs generate.
	AutoGenerated DocType = iota

	// TemplateBased files are only created if missing (unless --force).
	TemplateBased
)

// DocFile defines a single documentation file to generate per FR-13.2.
type DocFile struct {
	// Name is the output filename (e.g., "AGENTS.md").
	Name string

	// TemplateName is the Go template name (e.g., "agents.md.tmpl").
	TemplateName string

	// Type determines regeneration behavior.
	Type DocType
}

// allDocFiles lists all 11 documentation files per FR-13.2.
var allDocFiles = []DocFile{
	{Name: "AGENTS.md", TemplateName: "agents.md.tmpl", Type: TemplateBased},
	{Name: "CLAUDE.md", TemplateName: "claude.md.tmpl", Type: TemplateBased},
	{Name: "SKILL.md", TemplateName: "skill.md.tmpl", Type: TemplateBased},
	{Name: "CLI_REFERENCE.md", TemplateName: "cli_reference.md.tmpl", Type: AutoGenerated},
	{Name: "STATUS_MACHINE.md", TemplateName: "status_machine.md.tmpl", Type: AutoGenerated},
	{Name: "WORKFLOWS.md", TemplateName: "workflows.md.tmpl", Type: TemplateBased},
	{Name: "CONTEXT_CHAIN.md", TemplateName: "context_chain.md.tmpl", Type: TemplateBased},
	{Name: "BLOCKED_HANDLING.md", TemplateName: "blocked_handling.md.tmpl", Type: TemplateBased},
	{Name: "SESSION_PROTOCOL.md", TemplateName: "session_protocol.md.tmpl", Type: TemplateBased},
	{Name: "PATTERNS.md", TemplateName: "patterns.md.tmpl", Type: TemplateBased},
	{Name: "TROUBLESHOOTING.md", TemplateName: "troubleshooting.md.tmpl", Type: AutoGenerated},
}

// Generator produces documentation files per FR-13.1.
type Generator struct {
	outputDir string
	templates *template.Template
	data      *TemplateData
	logger    *slog.Logger
}

// GenerateResult describes the outcome of generating a single file.
type GenerateResult struct {
	File    string `json:"file"`
	Action  string `json:"action"` // "generated", "updated", "skipped"
	Message string `json:"message,omitempty"`
}

// NewGenerator creates a documentation generator from a filesystem template directory.
// templateDir is the directory containing Go template files.
// outputDir is where generated files are written (typically project/docs/).
func NewGenerator(templateDir, outputDir string, data *TemplateData, logger *slog.Logger) (*Generator, error) {
	if logger == nil {
		logger = slog.Default()
	}

	// Parse all templates.
	pattern := filepath.Join(templateDir, "*.tmpl")
	tmpl, err := template.ParseGlob(pattern)
	if err != nil {
		return nil, fmt.Errorf("parse templates from %s: %w", pattern, err)
	}

	return &Generator{
		outputDir: outputDir,
		templates: tmpl,
		data:      data,
		logger:    logger,
	}, nil
}

// NewEmbeddedGenerator creates a documentation generator using embedded templates.
// Uses the templates compiled into the binary via embed.FS per FR-13.1.
// outputDir is where generated files are written (typically project/docs/).
func NewEmbeddedGenerator(outputDir string, data *TemplateData, logger *slog.Logger) (*Generator, error) {
	if logger == nil {
		logger = slog.Default()
	}

	// Parse embedded templates from the templates/ subdirectory.
	tmpl, err := template.ParseFS(embeddedTemplates, "templates/*.tmpl")
	if err != nil {
		return nil, fmt.Errorf("parse embedded templates: %w", err)
	}

	return &Generator{
		outputDir: outputDir,
		templates: tmpl,
		data:      data,
		logger:    logger,
	}, nil
}

// EmbeddedTemplatesFS returns the embedded templates filesystem for external use.
func EmbeddedTemplatesFS() fs.FS {
	return embeddedTemplates
}

// Generate produces all 11 documentation files per FR-13.1.
// If force is true, all files are regenerated regardless of type.
// Returns results describing what happened to each file.
func (g *Generator) Generate(force bool) ([]GenerateResult, error) {
	// Ensure output directory exists.
	if err := os.MkdirAll(g.outputDir, 0o755); err != nil {
		return nil, fmt.Errorf("create docs dir %s: %w", g.outputDir, err)
	}

	var results []GenerateResult

	for _, doc := range allDocFiles {
		result, err := g.generateFile(doc, force)
		if err != nil {
			return results, fmt.Errorf("generate %s: %w", doc.Name, err)
		}
		results = append(results, result)
		g.logger.Info("doc generation",
			"file", result.File, "action", result.Action)
	}

	return results, nil
}

// generateFile handles a single documentation file.
func (g *Generator) generateFile(doc DocFile, force bool) (GenerateResult, error) {
	outPath := filepath.Join(g.outputDir, doc.Name)

	// Check if the file exists.
	exists := fileExists(outPath)

	// Template-based files: skip if exists and not forced.
	if doc.Type == TemplateBased && exists && !force {
		return GenerateResult{
			File:    doc.Name,
			Action:  "skipped",
			Message: "template-based file exists (use --force to regenerate)",
		}, nil
	}

	// Auto-generated or forced: check for markers if file exists.
	if exists && doc.Type == TemplateBased {
		// For template-based files with --force, check for auto-generated markers.
		updated, err := updateMarkedSections(outPath, g.templates, doc.TemplateName, g.data)
		if err == nil && updated {
			return GenerateResult{
				File:   doc.Name,
				Action: "updated",
			}, nil
		}
		// If no markers or error, fall through to full generation.
	}

	// Render the template.
	if err := g.renderTemplate(doc.TemplateName, outPath); err != nil {
		return GenerateResult{}, err
	}

	action := "generated"
	if exists {
		action = "updated"
	}

	return GenerateResult{File: doc.Name, Action: action}, nil
}

// renderTemplate executes a template and writes the result to a file.
func (g *Generator) renderTemplate(tmplName, outPath string) error {
	f, err := os.Create(outPath)
	if err != nil {
		return fmt.Errorf("create %s: %w", outPath, err)
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			g.logger.Error("close generated file", "path", outPath, "error", closeErr)
		}
	}()

	if err := g.templates.ExecuteTemplate(f, tmplName, g.data); err != nil {
		return fmt.Errorf("execute template %s: %w", tmplName, err)
	}

	return nil
}

// AllDocFiles returns the list of all documentation files for external use.
func AllDocFiles() []DocFile {
	result := make([]DocFile, len(allDocFiles))
	copy(result, allDocFiles)
	return result
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}
