// Copyright 2025-2026 HyperSWE
// SPDX-License-Identifier: Apache-2.0

package docs

import (
	"os"
	"path/filepath"
	"testing"
	"text/template"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestMarkers_AutoGeneratedSectionReplaced verifies marker-delimited content is updated.
func TestMarkers_AutoGeneratedSectionReplaced(t *testing.T) {
	tmpDir := t.TempDir()
	filePath := filepath.Join(tmpDir, "test.md")

	// Write file with markers and old content.
	existing := `# My Doc

Some human content.

<!-- AUTO-GENERATED: TOOLS -->
- old_tool_1
- old_tool_2
<!-- END AUTO-GENERATED -->

More human content.
`
	err := os.WriteFile(filePath, []byte(existing), 0o644)
	require.NoError(t, err)

	// Create a template that generates new content.
	tmpl := template.Must(template.New("test.md.tmpl").Parse(
		`# My Doc

<!-- AUTO-GENERATED: TOOLS -->
- new_tool_1
- new_tool_2
- new_tool_3
<!-- END AUTO-GENERATED -->
`))

	updated, err := updateMarkedSections(filePath, tmpl, "test.md.tmpl", &TemplateData{})
	require.NoError(t, err)
	assert.True(t, updated)

	content, err := os.ReadFile(filePath)
	require.NoError(t, err)

	// Auto-generated section should be updated.
	assert.Contains(t, string(content), "new_tool_3")
	assert.NotContains(t, string(content), "old_tool_1")

	// Human content should be preserved.
	assert.Contains(t, string(content), "Some human content.")
	assert.Contains(t, string(content), "More human content.")
}

// TestMarkers_HumanContentPreserved verifies content outside markers is untouched.
func TestMarkers_HumanContentPreserved(t *testing.T) {
	tmpDir := t.TempDir()
	filePath := filepath.Join(tmpDir, "test.md")

	existing := `# Customized Doc

This paragraph was carefully written by a human.

<!-- AUTO-GENERATED: STATUS -->
| From | To |
|------|----|
| open | done |
<!-- END AUTO-GENERATED -->

This conclusion was also written by a human.
And has multiple paragraphs.
`
	err := os.WriteFile(filePath, []byte(existing), 0o644)
	require.NoError(t, err)

	tmpl := template.Must(template.New("test.md.tmpl").Parse(
		`<!-- AUTO-GENERATED: STATUS -->
| From | To |
|------|----|
| open | in_progress |
| in_progress | done |
<!-- END AUTO-GENERATED -->
`))

	updated, err := updateMarkedSections(filePath, tmpl, "test.md.tmpl", &TemplateData{})
	require.NoError(t, err)
	assert.True(t, updated)

	content, err := os.ReadFile(filePath)
	require.NoError(t, err)

	assert.Contains(t, string(content), "carefully written by a human")
	assert.Contains(t, string(content), "conclusion was also written")
	assert.Contains(t, string(content), "in_progress | done")
}

// TestMarkers_MissingMarkers_FullGeneration verifies files without markers return false.
func TestMarkers_MissingMarkers_FullGeneration(t *testing.T) {
	tmpDir := t.TempDir()
	filePath := filepath.Join(tmpDir, "test.md")

	existing := `# Simple Doc

No markers here. Just plain content.
`
	err := os.WriteFile(filePath, []byte(existing), 0o644)
	require.NoError(t, err)

	tmpl := template.Must(template.New("test.md.tmpl").Parse("# New Content"))

	updated, err := updateMarkedSections(filePath, tmpl, "test.md.tmpl", &TemplateData{})
	require.NoError(t, err)
	assert.False(t, updated, "should return false when no markers found")
}

// TestMarkers_MultipleMarkers_AllReplaced verifies multiple sections are all updated.
func TestMarkers_MultipleMarkers_AllReplaced(t *testing.T) {
	tmpDir := t.TempDir()
	filePath := filepath.Join(tmpDir, "test.md")

	existing := `# Doc

<!-- AUTO-GENERATED: SECTION_A -->
old A content
<!-- END AUTO-GENERATED -->

Human content between sections.

<!-- AUTO-GENERATED: SECTION_B -->
old B content
<!-- END AUTO-GENERATED -->
`
	err := os.WriteFile(filePath, []byte(existing), 0o644)
	require.NoError(t, err)

	tmpl := template.Must(template.New("test.md.tmpl").Parse(
		`<!-- AUTO-GENERATED: SECTION_A -->
new A content
<!-- END AUTO-GENERATED -->

<!-- AUTO-GENERATED: SECTION_B -->
new B content
<!-- END AUTO-GENERATED -->
`))

	updated, err := updateMarkedSections(filePath, tmpl, "test.md.tmpl", &TemplateData{})
	require.NoError(t, err)
	assert.True(t, updated)

	content, err := os.ReadFile(filePath)
	require.NoError(t, err)

	assert.Contains(t, string(content), "new A content")
	assert.Contains(t, string(content), "new B content")
	assert.NotContains(t, string(content), "old A content")
	assert.NotContains(t, string(content), "old B content")
	assert.Contains(t, string(content), "Human content between sections.")
}

// TestExtractSections_ParsesMultiple verifies section extraction.
func TestExtractSections_ParsesMultiple(t *testing.T) {
	content := `<!-- AUTO-GENERATED: FOO -->
foo content
<!-- END AUTO-GENERATED -->
middle
<!-- AUTO-GENERATED: BAR -->
bar content
<!-- END AUTO-GENERATED -->`

	sections := extractSections(content)
	assert.Len(t, sections, 2)
	assert.Equal(t, "foo content", sections["FOO"])
	assert.Equal(t, "bar content", sections["BAR"])
}

// TestWrapAutoGenerated_CorrectFormat verifies marker wrapping.
func TestWrapAutoGenerated_CorrectFormat(t *testing.T) {
	result := WrapAutoGenerated("TEST", "some content")
	assert.Contains(t, result, "<!-- AUTO-GENERATED: TEST -->")
	assert.Contains(t, result, "some content")
	assert.Contains(t, result, "<!-- END AUTO-GENERATED -->")
}
