// Copyright 2025-2026 HyperSWE
// SPDX-License-Identifier: Apache-2.0

package docs

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"
)

// markerPattern matches auto-generated section markers per FR-13.3a.
// Format: <!-- AUTO-GENERATED: SECTION_NAME --> ... <!-- END AUTO-GENERATED -->
var markerPattern = regexp.MustCompile(
	`(?s)(<!-- AUTO-GENERATED: (\w+) -->)(.*?)(<!-- END AUTO-GENERATED -->)`,
)

// updateMarkedSections replaces only auto-generated sections in an existing file.
// Human-edited content outside markers is preserved per FR-13.3a.
// Returns true if any sections were updated.
func updateMarkedSections(
	filePath string,
	templates *template.Template,
	tmplName string,
	data *TemplateData,
) (bool, error) {
	existing, err := os.ReadFile(filePath)
	if err != nil {
		return false, fmt.Errorf("read %s: %w", filePath, err)
	}

	// If no markers found, return false (caller should do full generation).
	if !markerPattern.Match(existing) {
		return false, nil
	}

	// Render the full template to extract new section content.
	var rendered bytes.Buffer
	if err := templates.ExecuteTemplate(&rendered, tmplName, data); err != nil {
		return false, fmt.Errorf("render template %s: %w", tmplName, err)
	}

	// Extract new sections from the rendered template.
	newSections := extractSections(rendered.String())
	if len(newSections) == 0 {
		return false, nil
	}

	// Replace sections in the existing content.
	updated := false
	result := markerPattern.ReplaceAllStringFunc(string(existing), func(match string) string {
		submatch := markerPattern.FindStringSubmatch(match)
		if len(submatch) < 5 {
			return match
		}

		sectionName := submatch[2]
		openTag := submatch[1]
		closeTag := submatch[4]

		newContent, ok := newSections[sectionName]
		if !ok {
			return match
		}

		updated = true
		return openTag + "\n" + newContent + "\n" + closeTag
	})

	if !updated {
		return false, nil
	}

	cleanPath := filepath.Clean(filePath)
	if err := os.WriteFile(cleanPath, []byte(result), 0o644); err != nil { //nolint:gosec // filePath is from internal doc generator, not user input
		return false, fmt.Errorf("write %s: %w", filePath, err)
	}

	return true, nil
}

// extractSections parses marker-delimited sections from rendered template content.
func extractSections(content string) map[string]string {
	sections := make(map[string]string)

	matches := markerPattern.FindAllStringSubmatch(content, -1)
	for _, match := range matches {
		if len(match) >= 4 {
			name := match[2]
			body := strings.TrimSpace(match[3])
			sections[name] = body
		}
	}

	return sections
}

// WrapAutoGenerated wraps content with auto-generated markers.
// Used in templates to mark sections that should be auto-updated.
func WrapAutoGenerated(sectionName, content string) string {
	return fmt.Sprintf(
		"<!-- AUTO-GENERATED: %s -->\n%s\n<!-- END AUTO-GENERATED -->",
		sectionName, content,
	)
}
