// Copyright 2025-2026 HyperSWE
// SPDX-License-Identifier: Apache-2.0

// Package docs implements the plugin installer for IDE-specific skill file deployment.
// Writes skill files, reference checklists, and MCP configuration to the correct
// locations for Claude Code, Cursor, and Windsurf per the approved plan.
package docs

import (
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"text/template"
)

// skillDocFiles lists the 5 skill templates per the plan.
var skillDocFiles = []DocFile{
	{Name: "mtix-task-execution.md", TemplateName: "task_execution.md.tmpl", Type: AutoGenerated},
	{Name: "mtix-planning.md", TemplateName: "planning.md.tmpl", Type: AutoGenerated},
	{Name: "mtix-review.md", TemplateName: "review.md.tmpl", Type: AutoGenerated},
	{Name: "mtix-multi-agent.md", TemplateName: "multi_agent.md.tmpl", Type: AutoGenerated},
	{Name: "mtix-admin.md", TemplateName: "admin.md.tmpl", Type: AutoGenerated},
}

// referenceDocFiles lists the 4 compliance reference checklists.
var referenceDocFiles = []DocFile{
	{Name: "do-178c-checklist.md", TemplateName: "do_178c_checklist.md.tmpl", Type: AutoGenerated},
	{Name: "iec-62304-checklist.md", TemplateName: "iec_62304_checklist.md.tmpl", Type: AutoGenerated},
	{Name: "nasa-std-8739-checklist.md", TemplateName: "nasa_std_8739_checklist.md.tmpl", Type: AutoGenerated},
	{Name: "mil-std-498-checklist.md", TemplateName: "mil_std_498_checklist.md.tmpl", Type: AutoGenerated},
}

// SkillDocFiles returns the list of skill documentation files.
func SkillDocFiles() []DocFile {
	result := make([]DocFile, len(skillDocFiles))
	copy(result, skillDocFiles)
	return result
}

// ReferenceDocFiles returns the list of reference checklist files.
func ReferenceDocFiles() []DocFile {
	result := make([]DocFile, len(referenceDocFiles))
	copy(result, referenceDocFiles)
	return result
}

// PluginInstaller writes skill files and configuration to IDE-specific locations.
type PluginInstaller struct {
	projectDir string
	data       *TemplateData
	logger     *slog.Logger
	templates  *template.Template
}

// NewPluginInstaller creates a plugin installer for the given project directory.
func NewPluginInstaller(projectDir string, data *TemplateData, logger *slog.Logger) *PluginInstaller {
	if logger == nil {
		logger = slog.Default()
	}

	// Parse skill templates from embedded FS.
	tmpl, err := template.ParseFS(embeddedTemplates,
		"templates/skills/*.tmpl",
		"templates/skills/references/*.tmpl",
	)
	if err != nil {
		// Log error but don't fail construction — Install will fail later.
		logger.Error("parse skill templates", "error", err)
	}

	return &PluginInstaller{
		projectDir: projectDir,
		data:       data,
		logger:     logger,
		templates:  tmpl,
	}
}

// InstallResult describes the outcome of installing a single file.
type InstallResult struct {
	File   string `json:"file"`
	Path   string `json:"path"`
	Action string `json:"action"` // "installed", "updated"
}

// Install writes skill files and configuration for the specified target IDE.
// Supported targets: "claude-code", "cursor", "windsurf".
// If global is true, writes to ~/.claude/skills/ instead of project-local.
func (p *PluginInstaller) Install(target string, global bool) ([]InstallResult, error) {
	switch target {
	case "claude-code":
		return p.installClaudeCode(global)
	default:
		return nil, fmt.Errorf("unsupported target: %s (supported: claude-code, cursor, windsurf)", target)
	}
}

// installClaudeCode writes skill files for Claude Code.
func (p *PluginInstaller) installClaudeCode(global bool) ([]InstallResult, error) {
	if p.templates == nil {
		return nil, fmt.Errorf("skill templates not loaded")
	}

	// Determine skill directory.
	skillDir := p.claudeSkillDir(global)
	refDir := filepath.Join(skillDir, "references")

	// Ensure directories exist.
	if err := os.MkdirAll(refDir, 0o755); err != nil {
		return nil, fmt.Errorf("create skill directories: %w", err)
	}

	var results []InstallResult

	// Write skill files.
	for _, doc := range skillDocFiles {
		result, err := p.renderToFile(doc, skillDir)
		if err != nil {
			return results, fmt.Errorf("install skill %s: %w", doc.Name, err)
		}
		results = append(results, result)
	}

	// Write reference files.
	for _, doc := range referenceDocFiles {
		result, err := p.renderToFile(doc, refDir)
		if err != nil {
			return results, fmt.Errorf("install reference %s: %w", doc.Name, err)
		}
		results = append(results, result)
	}

	return results, nil
}

// claudeSkillDir returns the skill directory for Claude Code.
func (p *PluginInstaller) claudeSkillDir(global bool) string {
	if global {
		home, err := os.UserHomeDir()
		if err != nil {
			home = os.Getenv("HOME")
		}
		return filepath.Join(home, ".claude", "skills")
	}
	return filepath.Join(p.projectDir, ".claude", "skills")
}

// renderToFile renders a template to a file in the target directory.
func (p *PluginInstaller) renderToFile(doc DocFile, dir string) (InstallResult, error) {
	outPath := filepath.Join(dir, doc.Name)

	action := "installed"
	if fileExists(outPath) {
		action = "updated"
	}

	f, err := os.Create(outPath)
	if err != nil {
		return InstallResult{}, fmt.Errorf("create %s: %w", outPath, err)
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			p.logger.Error("close file", "path", outPath, "error", closeErr)
		}
	}()

	if err := p.templates.ExecuteTemplate(f, doc.TemplateName, p.data); err != nil {
		return InstallResult{}, fmt.Errorf("render %s: %w", doc.TemplateName, err)
	}

	p.logger.Info("plugin install", "file", doc.Name, "action", action, "path", outPath)

	return InstallResult{
		File:   doc.Name,
		Path:   outPath,
		Action: action,
	}, nil
}
