#!/usr/bin/env bash
# Generate a Version Description Document (VDD) for a release.
# Usage: ./scripts/generate-vdd.sh <tag> <checksums-file>
# Output: VDD-<tag>.md in the current directory.

set -euo pipefail

TAG="${1:?Usage: generate-vdd.sh <tag> <checksums-file>}"
CHECKSUMS="${2:?Usage: generate-vdd.sh <tag> <checksums-file>}"
VERSION="${TAG#v}"
VDD="VDD-${TAG}.md"
PREV_TAG=$(git describe --tags --abbrev=0 "${TAG}^" 2>/dev/null || echo "")

cat > "$VDD" <<HEADER
# Version Description Document — ${TAG}

**Project:** mtix
**Version:** ${VERSION}
**Tag:** ${TAG}
**Date:** $(date -u +"%Y-%m-%d")
**Commit:** $(git rev-parse --short HEAD)

---

## Changelog
HEADER

if [ -n "$PREV_TAG" ]; then
  echo "" >> "$VDD"
  echo "Changes since ${PREV_TAG}:" >> "$VDD"
  echo "" >> "$VDD"
  git log "${PREV_TAG}..${TAG}" --pretty=format:"- %s" --no-merges >> "$VDD" 2>/dev/null || echo "- Initial release" >> "$VDD"
else
  echo "" >> "$VDD"
  echo "Initial release." >> "$VDD"
fi

cat >> "$VDD" <<'SECTION'

---

## Artifact Inventory

| File | SHA-256 |
|------|---------|
SECTION

if [ -f "$CHECKSUMS" ]; then
  while IFS= read -r line; do
    sha=$(echo "$line" | awk '{print $1}')
    file=$(echo "$line" | awk '{print $2}')
    echo "| ${file} | \`${sha}\` |" >> "$VDD"
  done < "$CHECKSUMS"
else
  echo "| (checksums file not found) | — |" >> "$VDD"
fi

cat >> "$VDD" <<'SECTION'

---

## Known Issues

SECTION

# Try to get open/blocked tasks from mtix
MTIX_BIN=""
if command -v mtix &>/dev/null; then
  MTIX_BIN="mtix"
elif [ -x "./mtix" ]; then
  MTIX_BIN="./mtix"
elif [ -x "./dist/mtix_linux_amd64_v1/mtix" ]; then
  MTIX_BIN="./dist/mtix_linux_amd64_v1/mtix"
fi

if [ -n "$MTIX_BIN" ]; then
  OPEN_COUNT=$($MTIX_BIN list --status open --json 2>/dev/null | grep -c '"id"') || OPEN_COUNT=0
  BLOCKED_COUNT=$($MTIX_BIN list --status blocked --json 2>/dev/null | grep -c '"id"') || BLOCKED_COUNT=0
  echo "- Open tasks: ${OPEN_COUNT}" >> "$VDD"
  echo "- Blocked tasks: ${BLOCKED_COUNT}" >> "$VDD"
  echo "" >> "$VDD"
  if [ "$BLOCKED_COUNT" -gt 0 ]; then
    echo "### Blocked Tasks" >> "$VDD"
    echo "" >> "$VDD"
    $MTIX_BIN list --status blocked 2>/dev/null >> "$VDD" || true
    echo "" >> "$VDD"
  fi
else
  echo "- mtix binary not available — run mtix list --status open,blocked for current issues." >> "$VDD"
fi

cat >> "$VDD" <<'SECTION'

---

## Software Metrics

SECTION

if [ -f "coverage.out" ]; then
  echo "### Test Coverage" >> "$VDD"
  echo "" >> "$VDD"
  echo '```' >> "$VDD"
  go tool cover -func=coverage.out 2>/dev/null | grep -E "^(total|.*/$)" >> "$VDD" || echo "Coverage data not available" >> "$VDD"
  echo '```' >> "$VDD"
  echo "" >> "$VDD"
fi

echo "### Test Summary" >> "$VDD"
echo "" >> "$VDD"
TEST_COUNT=$(go test ./... -count=1 -json 2>/dev/null | grep -c '"Test"' || echo "unknown")
echo "- Test count: ${TEST_COUNT}" >> "$VDD"
echo "- Race detector: enabled in preflight" >> "$VDD"
echo "" >> "$VDD"

cat >> "$VDD" <<SECTION

---

## Build Environment

- **Go:** $(go version 2>/dev/null | awk '{print $3}' || echo "unknown")
- **OS:** $(uname -s) $(uname -m)
- **Commit:** $(git rev-parse HEAD)

See BUILD-ENVIRONMENT.json for full CI build details.

---

## Installation

### Upgrade

\`\`\`bash
# 1. Backup current state
mtix export > backup-\$(date +%Y%m%d).json

# 2. Install new version
brew upgrade mtix
# or download from GitHub Releases

# 3. Verify
mtix --version
mtix verify
\`\`\`

### Rollback

\`\`\`bash
# 1. Install previous version
brew install hyper-swe/tap/mtix@${PREV_TAG:-previous}
# or download previous release binary

# 2. Restore from backup if needed
mtix import backup-YYYYMMDD.json --mode replace
\`\`\`

---

## Compatibility

- **Go:** 1.25+
- **Node.js:** 18+ (web UI build only)
- **Platforms:** darwin (amd64, arm64), linux (amd64, arm64), windows (amd64, arm64)
- **Database:** SQLite (embedded, no external dependencies)

---

*Generated by scripts/generate-vdd.sh*
SECTION

echo "Generated ${VDD}"
